// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLeFo4uuKadi76FyyZgGOkBkZXFiSUyxg',
    appId: '1:490052007225:web:3986ddf6d5628df0fd24e8',
    messagingSenderId: '490052007225',
    projectId: 'app-dev-final-c4845',
    authDomain: 'app-dev-final-c4845.firebaseapp.com',
    storageBucket: 'app-dev-final-c4845.appspot.com',
    measurementId: 'G-3LENNRCH3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiMPgtU7sPC9esxbSOxay1P0Qvxztdl_U',
    appId: '1:490052007225:android:4a19ca13981f1e23fd24e8',
    messagingSenderId: '490052007225',
    projectId: 'app-dev-final-c4845',
    storageBucket: 'app-dev-final-c4845.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYX0XHLFAxuO6ljf1rKLKToUSMYPOUNzo',
    appId: '1:490052007225:ios:28d7dd84d6d62feefd24e8',
    messagingSenderId: '490052007225',
    projectId: 'app-dev-final-c4845',
    storageBucket: 'app-dev-final-c4845.appspot.com',
    iosBundleId: 'com.example.finalProjectV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYX0XHLFAxuO6ljf1rKLKToUSMYPOUNzo',
    appId: '1:490052007225:ios:28d7dd84d6d62feefd24e8',
    messagingSenderId: '490052007225',
    projectId: 'app-dev-final-c4845',
    storageBucket: 'app-dev-final-c4845.appspot.com',
    iosBundleId: 'com.example.finalProjectV1',
  );
}
